version: '2'



services:

  shared:
       image: busybox:latest
       volumes:
         - ./:/var/www/html

  web:
      image: nginx:latest
      ports:
        - "8081:80"

      volumes_from:
        - shared

      volumes: 
        - ./site.conf:/etc/nginx/conf.d/default.conf
      environment: 
          XDEBUG_CONFIG: remote_host=<your_ip_address>
      links:
          -   php
  php:
      image: php:7-fpm

      volumes_from:
        - shared


  mysql:
      image: phpstorm/mysql
      ports:
        - "33056:3306"
      volumes:
        - ./data:/var/lib/mysql
